services:

  pp-app:
    build: 
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./poputka:/poputka
    environment:
      - PP_DJANGO_SECRET_KEY=${PP_DJANGO_SECRET_KEY}
      - PP_DB_HOST=${PP_DB_HOST}
      - PP_POSTGRES_DB=${PP_POSTGRES_DB}
      - PP_POSTGRES_USER=${PP_POSTGRES_USER}
      - PP_POSTGRES_PASSWORD=${PP_POSTGRES_PASSWORD}
      - PP_EMAIL_HOST_USER=${PP_EMAIL_HOST_USER}
      - PP_EMAIL_HOST_PASS=${PP_EMAIL_HOST_PASS}
      

    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - pp_database

  pp_database:
    image: postgres:16.1-alpine3.19
    restart: always
    volumes:
      - ~/.pg/pg_data/poputka_data:/var/lib/postgresql/data
    environment:
      - PP_DB_HOST=${PP_DB_HOST}
      - PP_POSTGRES_USER=${PP_POSTGRES_USER}
      - PP_POSTGRES_PASSWORD=${PP_POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  redis:
    image: redis:7.2-alpine
    hostname: redis

  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - ./poputka:/poputka
    links:
      - redis
    depends_on:
      - redis
    