# Generated by Django 5.0 on 2024-01-21 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_place', models.CharField(max_length=30, verbose_name='Откуда')),
                ('to_place', models.CharField(max_length=30, verbose_name='Куда')),
                ('ride_datetime', models.DateTimeField(verbose_name='Дата')),
                ('seats_count', models.IntegerField(verbose_name='Свободные места')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
