# Generated by Django 5.0 on 2024-01-21 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ride',
            options={'verbose_name': 'Поездка', 'verbose_name_plural': 'Поездки'},
        ),
    ]
