# Generated by Django 5.0 on 2024-02-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_feedback_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='text',
            field=models.CharField(null=True, verbose_name='Описание'),
        ),
    ]
