# Generated by Django 5.0 on 2024-01-21 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Пользователь', max_length=30)),
                ('birthday', models.DateField(blank=True)),
                ('rating', models.FloatField(blank=True)),
                ('avatar', models.ImageField(blank=True, default=None, null=True, upload_to='avatars')),
                ('ride_count', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
