# Generated by Django 5.0 on 2024-01-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_last_name_remove_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='avatars', verbose_name='Изображение профиля'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='Пользователь', max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.FloatField(blank=True, null=True, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ride_count',
            field=models.IntegerField(default=0, verbose_name='Всего поездок'),
        ),
    ]
