# Generated by Django 5.0 on 2024-02-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatars/nophoto.png', upload_to='avatars', verbose_name='Изображение профиля'),
        ),
    ]
